on:
  release:
    types: [created]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.0'

      - name: Restore dependencies
        run: dotnet restore Cloud.Net.sln

      - name: Build
        run: dotnet build Cloud.Net.sln --configuration Release --no-restore

      - name: Pack
        run: dotnet pack Cloud.Net.sln --configuration Release --no-build --output ./nupkgs -p:PackageVersion=${{ github.ref_name }}

      - name: Publish to GitHub Packages
        run: dotnet nuget push ./nupkgs/*.nupkg --source "https://nuget.pkg.github.com/feedboards/index.json" --api-key ${{ secrets.GH_TOKEN }}
        env:
          OWNER: feedboards

      - name: Cleanup
        run: rm -rf ./nupkgs
